# -- 主菜单 --

[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 40


# -- 搜索 --
[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"


# -- 页脚菜单 --
[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "文章"
  pageRef = "posts"
  weight = 20
